### ISSUE TITLE
Konatsu Skills Missing

### ISSUE THREAD

**Issue by cronox123** [CKMud-Mudlet-Scripts/CK#12]
Noticed the other day after remorting that Autolearn didn't level up the racial skills: Moonlight Pierce, Zephyr Slice, or Nova Symphony, first two being Physical Attacks and the later an AoE attack.

I added them manually to the Attacks and Skills scripts and the bot seemed to knock them out after that.

**Comment by fried** [comment]
fixed in a9a23863afeb5423e0f42b864cb445b9ad6dd5b6
